ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "ingredient_names" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "uses" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "review_summary" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "sources" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
